version: "3.9"

services:
  server:
    container_name: server_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=postgres
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_container
    image: postgres:17.6
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      device: ./data/postgres
      o: bind
  pgadmin:
    driver: local
    driver_opts:
      type: none
      device: ./data/pgadmin
      o: bind
